/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    LoginForm: typeof import('./src/components/login/LoginForm.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    RoleList: typeof import('./src/components/role/RoleList.vue')['default']
    RoleListItem: typeof import('./src/components/role/RoleListItem.vue')['default']
    RoleTree: typeof import('./src/components/role/RoleTree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
