/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    LoginForm: typeof import('./src/components/login/LoginForm.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MainMenu: typeof import('./src/components/mainMenu/index.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    MenuItem: typeof import('./src/components/mainMenu/menuItem.vue')['default']
    RoleList: typeof import('./src/components/role/RoleList.vue')['default']
    RoleListItem: typeof import('./src/components/role/RoleListItem.vue')['default']
    RoleTree: typeof import('./src/components/role/RoleTree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenuItem: typeof import('./src/components/mainMenu/subMenuItem.vue')['default']
    Template: typeof import('./src/components/template.vue')['default']
  }
}
